spring:
  application:
    name: NBEProject

  thymeleaf:
    cache: false
    prefix: classpath:templates/

  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}

  # security 설정
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 구글 클라이언트 아이디
            client-secret: 구글 시크릿
            scope: #어떤 정보 가져올건지
              - email
              - profile
          facebook:
            client-id: 페북 클라 아이디
            client-secret: 페북 시크릿
            scope: # 접근권한
              - email
              - public_profile
          naver:
            client-id: 네이버 클라 아이디
            client-secret: 네이버 시크릿
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
          kakao:
            client-id: 카카오 클라 아이디
            client-secret: 카카오 시크릿(아마 새로 발급필요) [내 애플리케이션] > [카카오 로그인] > [보안]에서 [코드 생성] https://developers.kakao.com/docs/latest/ko/kakaologin/prerequisite#consent-item
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post

        #provider 제공
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 30m


app:
  # 페이징 관련 세팅값
  pagination:
    write_pages: 5 # 한 [페이징] 당 몇 개의 페이지를 표시
    page_rows: 5 # 한 '페이지' 에 몇 개의 글을 리스트 할 지?

  # 파일 업로드 경로
  upload:
    path: upload